### PR TITLE
feat: support empty snapshot

### PR DESCRIPTION
**Pull request by apepkuss**
Major changes:

- Introduce `llama-api-server.wasm` into installer and CLI tool
- Improve CLI tool

### CODE REVIEW

**Comment by juntao** [comment]
I have two issues when the snapshot field is empty:

1. When we start `llama-api-server.wasm`, we still need to start both the chat and embedding models. The `/embedding` endpoint should work in this setup.  Currently, only the chat model is started.
2. The `gaianet init` command fails to update the `gaianet-domain/frpc.toml` file with the node ID from `nodeid.json` or `config.json`.

**Comment by apepkuss** [comment]
@juntao 
1. Different from `rag-api-server`, `llama-api-server` only supports a single model, chat or embedding, instead of both at the same time.
2. This PR only introduces a minor change in `init` to check if `snapshot` is empty or not before calling `create_collection` function. No code change covers the registry.

**Comment by apepkuss** [comment]
Ok. We need to provide support for the following three scenarios in `llama-api-server`, right?

1. Only chat model
2. Only embedding model
3. Both chat and embedding models

**Comment by juntao** [comment]
> Ok. We need to provide support for the following three scenarios in `llama-api-server`, right?
> 
> 1. Only chat model
> 2. Only embedding model
> 3. Both chat and embedding models

Yes. But for a MVP, 1 + 3 would suffice.

**Comment by apepkuss** [comment]
Ok. To satisfy the requirements, we have to refactor the CLI and the handlers in `llama-api-server` and release a new version. I'll close this PR first and reopen it once `llama-api-server` gets ready.

**Pull request closed without merging**
